### ISSUE TITLE
Times of Event do not display correct times

### ISSUE THREAD

**Issue by christianhelp** [acmutsa/HackKit#48]
### Description

* As of now, the time of an event does not reflect correctly due to issues with how the time is converted from the server.

### Requirements

* Time of event should reflect correctly for a user in any time zone
* The data for the event should still be able to be rendered by the server

**Comment by Lermatroid** [comment]
Ok starting review! Just a heads up though its not that the headers are on the edge or not work in production. It does work in Vercel production and preview environments, but not on non-vercel platforms / edge. TLDR: vendor lock-in for people who do not want to host on vercel 👍
